### ISSUE TITLE
Fix Fonts Styles 

### ISSUE THREAD

**Issue by coderjojo** [NewbieDevs/DSEWebApp#6]
Fonts in footer of all Web Pages are getting different values.

Add common class to all the fonts in footer.

**Comment by ccmetz** [comment]
Hey @coderjojo , I can take this one 🙂

**Comment by Pratik7717** [comment]
I did a PR #7 ..Please review and merge the changes.

**Comment by coderjojo** [comment]
> Hey @coderjojo , I can take this one slightly_smiling_face . Just for clarification, what values are different between all of the fonts in the footer? What would you like to be the same between them?

Thanks for your interest but @Pratik7717 had already made a PR for this issue.
